# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /Users/distiller/project/recipes/intarna, last modified Mon Mar  2 04:40:55 2020
# ------------------------------------------------

package:
    name: intarna
    version: 3.2.0
source:
    sha256: 6b6562579af5aa336e0bad5a678d7790cae537ce46de72d5b5fb2650f77263b9
    url: https://github.com/BackofenLab/IntaRNA/releases/download/v3.2.0/intaRNA-3.2.0.tar.gz
build:
    number: '0'
    string: h547e0c7_0
requirements:
    build:
        - cctools 895 h7512d6f_0
        - clang 4.0.1 h662ec87_0
        - clang_osx-64 4.0.1 h1ce6c1d_17
        - clangxx 4.0.1 hc9b4283_0
        - clangxx_osx-64 4.0.1 h22b1bf0_17
        - compiler-rt 4.0.1 h5487866_0
        - ld64 274.2 h7c2db76_0
        - libcxx 4.0.1 h579ed51_0
        - libcxxabi 4.0.1 hebd6815_0
        - llvm 4.0.1 hc748206_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
    host:
        - boost-cpp 1.70.0 h75728bb_2
        - bzip2 1.0.8 h0b31af3_2
        - ca-certificates 2019.11.28 hecc5488_0
        - doxygen 1.8.16 h72f44dd_1
        - icu 64.2 h6de7cb9_1
        - libcxx 9.0.1 1
        - libffi 3.2.1 h6de7cb9_1006
        - libiconv 1.15 h01d97ff_1005
        - llvm-openmp 9.0.1 h28b9765_2
        - ncurses 6.1 h0a44026_1002
        - openssl 1.1.1d h0b31af3_0
        - perl 5.26.2 haec8ef5_1006
        - pkg-config 0.29.2 hdc84dc8_1006
        - pkgconfig 1.3.1 py37_1002
        - python 3.7.6 h5c2c468_2
        - readline 8.0 hcfe32e1_0
        - sqlite 3.30.1 h93121df_0
        - tk 8.6.10 hbbe82c9_0
        - viennarna 2.4.14 py37hfbae3c0_0
        - xz 5.2.4 h1de35cc_1001
        - zlib 1.2.11 h0b31af3_1006
    run:
        - boost-cpp >=1.70.0,<1.70.1.0a0
        - libcxx >=4.0.1
        - llvm-openmp >=9.0.1
        - viennarna >=2.4.14,<2.5.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - IntaRNA -h
        - IntaRNA -t CCCCCCCCGGGGGGGGGGGGGG -q CCCCCCC
about:
    home: https://github.com/BackofenLab/IntaRNA
    license: MIT
    summary: Efficient RNA-RNA interaction prediction incorporating seeding and accessibility
        of interacting sites
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:intarna
        - doi:10.1093/bioinformatics/btn544
        - doi:10.1093/nar/gkx279
        - doi:10.1093/nar/gky329
    recipe-maintainers:
        - BackofenLab
        - martin-raden
